#!/usr/bin/env bash

print_hline()
{
    local char="$1" times="$2"

    for ((i=0;i<times;i++)); do
        echo -n "${char}"
    done
    echo
}

print_delimiter()
{
    echo $COLUMNS >> log.log
    local filename="$1"
    print_hline "─" $(tput columns)
    echo "Cheatsheet: ${filename}"
    print_hline "─" $(tput columns)
}

filename="$1"
display="$2"
display=${display:="preview"}

DISPLAY_PREVIEW="cat"
DISPLAY_TERMINAL="cat"

if command -v bat &> /dev/null; then
    DISPLAY_PREVIEW="command bat --color=always"
    DISPLAY_TERMINAL="command bat -pp --color=always"
fi

if [[ "${display}" == "preview" ]]; then
    ${DISPLAY_PREVIEW} "${filename}"
    exit 0
fi

if [[ "${display}" == "terminal" ]]; then
    print_delimiter $(basename "${filename}")
    ${DISPLAY_TERMINAL} "${filename}"
    print_delimiter $(basename "${filename}")
    # if [[ "${toolname}" == "bat" && $(tput lines) -ge $(wc -l < "${filename}") ]]; then
    #     ${CAT} --color=always "${filename}"
    # else
    #     print_delimiter "${filename}"
    #     cat "${filename}"
    #     print_delimiter "${filename}"
    # fi
fi
