#!/bin/bash

declare -A results

read -a keywords <<< "${1}"

for k in "${keywords[@]}" ""; do
    cur_results=( $(grep -l -r -E "KEYWORDS: .*${k}" --include=\*.chsht.\*) )
    
    for r in "${cur_results[@]}"; do
        if [[ ! -v results["${r}"] ]] ; then
            results["${r}"]=0
        else
            results["${r}"]=$(( ${results["${r}"]} + 1 ))
        fi
    done
done

max=0
for key in "${!results[@]}"; do
    if [[ $max -lt ${results["${key}"]} ]]; then
        max=${results["${key}"]}
    fi
done

for key in "${!results[@]}"; do
    if [[ ${results["${key}"]} -eq $max  ]]; then
        echo "$key"
    fi
done

# echo "grep -l -r -E ${search_option} --include=\*.chsht.\*"
# grep -l -r -E "${search_option}" --include=\*.chsht.\*
