#!/bin/bash

print_hline()
{
    local char="$1" times="$2"

    for ((i=0;i<times;i++)); do
        echo -n "${char}"
    done
    echo
}

print_delimiter()
{
    local filename="$1"
    print_hline "─" ${#filename}
    echo "${filename}"
    print_hline "─" ${#filename}
}

filename="$1"
toolname="$2"
toolname=${toolname:="bat"}
display="$3"
display=${display:="preview"}

if command -v bat; then
    BAT="bat --color=always"
else
    BAT="cat"
fi

if [[ "${display}" == "preview" ]]; then
    ${BAT} "${filename}"
    exit 0
fi

if [[ "${display}" == "terminal" ]]; then
    if [[ "${toolname}" == "bat" && $(tput lines) -ge $(wc -l < "${filename}") ]]; then
        ${BAT} --color=always "${filename}"
    else
        print_delimiter "${filename}"
        cat "${filename}"
        print_delimiter "${filename}"
    fi
fi
