#!/bin/bash

CHEATSHEETS_DIR=$(dirname "$0")
export CHEATSHEETS_DIR

# shellcheck disable=SC2016
_cheatsheet_search "$@" | fzf --preview-window=right,50% --disabled --ansi \
    --bind='change:reload(_cheatsheet_search {q})'\
    --bind='focus:change-preview(bat --color=always $(find ${CHEATSHEETS_DIR} -name {}))'\
    --bind='enter:become(display_cheatsheet $(find ${CHEATSHEETS_DIR} -name {}))'\
    --bind='ctrl-b:become([ -z ${INCLUDE_BASH_BIBLE+x} ] && export INCLUDE_BASH_BIBLE=yes || unset INCLUDE_BASH_BIBLE; cheatsheet {q})'     # toggles the search in bash bible
